### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by larsnystrom** [phpbrew/PEARX#7]
I'm behind a corporate proxy, which causes PEARX to "fail to open stream" when using `file_get_contents()` to download things.

Here's an example of how this was solved in phpbrew: https://github.com/phpbrew/phpbrew/pull/210/commits/1fe7a79f0aea211201a218db6ff8e34204113738

**Comment by Furgas** [comment]
Also, there is some esotheric 'downloader' support baked in (https://github.com/phpbrew/PEARX/blob/master/src/PEARX/Core.php#L32), but `file_get_contents` is fired nevertheless two lines after that...

**Comment by c9s** [comment]
@Furgas thanks for reporting this, it would be great if you can come up with a PR :-)
